# Just rename it to config.yaml.
host: "::"
port: 80
workers: 2
domains:
  - siiway.org
  - siiway.top
  - wss.moe
  - siinodes.dpdns.org
  - siiway.qzz.io
log:
  level: debug
  rotation: 10M
  retention: 5
